"""changed debates table

Revision ID: 4c0db77db963
Revises: b47f8477e7db
Create Date: 2024-07-12 16:56:23.837702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c0db77db963'
down_revision: Union[str, None] = 'b47f8477e7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('debate', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('debate', 'created_at')
    # ### end Alembic commands ###
