"""added finished state to the debates

Revision ID: 4bf5346e6b95
Revises: 4c0db77db963
Create Date: 2024-07-13 18:57:48.533868

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4bf5346e6b95"
down_revision: Union[str, None] = "4c0db77db963"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("debate", sa.Column("finished", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("debate", "finished")
    # ### end Alembic commands ###
